FROM python:3.8-buster
LABEL maintainer='Mike Kroutikov <mkroutikov@innodata.com>'

RUN apt update; apt install -y vim

COPY . /self

RUN cd /self; REDSTAGING=/self/.. REDDEBUG=true bash /self/build_scripts/build.sh

WORKDIR /pdfium/redstork

CMD [ "bash" ]

